Benefit/html
sepaev/reacteam-project pull request #16
Opened 2021-04-04 17:38 UTC by dimapashchenko1

2021-04-05 18:19 UTC, sepaev requested changes

2021-04-05 18:19 UTC, sepaev commented on src/partials/benefits.html
> +<!-- <section class="benefits" id="benefits">
Секция не может быть пустая

2021-04-05 18:28 UTC, zhitnyak submitted a review, later dismissed
вроде все норм, после мерджа нужно глянуть как расположится относительно соседних блоков

2021-04-06 12:14 UTC, al-burlachenko requested changes

2021-04-06 12:14 UTC, ol-nerium commented on src/sass/components/_program.scss
> +            top: 35%;
надо 27%, чтобы точка стояла ровно напротив пункта

2021-04-06 12:14 UTC, ol-nerium commented on src/sass/components/_program.scss
> +        border-left: 2px solid;
Бордер не совпадает с макетом. Гораздо проще сделать его псевдоелементом: 

Для этого .program__list надо дать position:relative; 

И добавить в scss новое медиаправило
 
.program__list {
    @media (max-width: 1279px) {
        &:before {
          content: '';
          display: block;
          width: 1px;
          background-color: #FFFFFF;
          position: absolute;
          top: 15px;
          left: -2px;
          height: 88%;
        }
      }
  @media (max-width: 767px) {
    &:before {
      content: '';
      display: block;
      width: 1px;
      background-color: #FFFFFF;
      position: absolute;
      top: 15px;
      left: -22px;
      height: 92%;
    }
  }
}

2021-04-06 12:14 UTC, ol-nerium commented on src/sass/components/_program.scss
> +        border-left: 2px solid;
Раз по ТЗ надо через бордеры, можно задать паддинг вместо маржина между семестрами и паддинг для левого отступа бордера: 

@media (max-width: 767px) {
    padding-left: 20px;
  }

  @media (max-width: 1279px) {
    padding-left: 50px;

    &:not(:last-child) {
      border-left: 1px solid;
      padding-bottom: 40px;
    }
  }

http://joxi.ru/12MaYdBckYbV82

2021-04-06 12:14 UTC, ol-nerium commented on src/sass/components/_program.scss
> +        border-left: 2px solid;
И вот такое правило для последнего куска бордера : 

.program__item:last-of-type .program__subtitle {
  @media (max-width: 767px) {
    border-left: 1px solid;
    padding-left: 20px;
    margin-left: -20px;
    &::after {
        left: -6px;
    }
  }

  @media (max-width: 1279px) {
    border-left: 1px solid;
    padding-left: 50px;
    margin-left: -50px;
    &::after {
        left: -6px;
    }
  }
}

2021-04-06 13:05 UTC, sepaev submitted a review, later dismissed

2021-04-06 16:14 UTC, sepaev submitted a review, later dismissed

2021-04-06 16:26 UTC, sepaev approved these changes

2021-04-06 16:27 UTC, merged

2021-04-06 16:43 UTC, al-burlachenko reviewed
апрув, чтобы можно было дальше пилить