Header
sepaev/reacteam-project pull request #7
Opened 2021-04-02 14:05 UTC by Dmytro78

2021-04-02 19:32 UTC, al-burlachenko commented on src/partials/header.html
> +            <p class="name"><span class="hell">адский</span> английский</p>
эта часть тоже должна быть ссылкой

2021-04-02 23:52 UTC, al-burlachenko requested changes

2021-04-02 23:52 UTC, ol-nerium commented on src/partials/header.html
> +            <p class="name"><span class="hell">адский</span> английский</p>
p class="name" и span class="hell" должны быть частью ссылки

2021-04-02 23:52 UTC, ol-nerium commented on src/partials/header.html
> +                <li class="links-menu"><a href="#" class="links-item">Программы обучения</a></li>
Есть смысл в том, чтобы поменять смысл имеен классов в ul и li местами, так как ul - это меню, а links и items- это его элементы. 
Например, сделать ul class="menu-links" , а его li class="menu-links__item" и ссылку, как a class="menu-links__item-link"

2021-04-02 23:52 UTC, ol-nerium commented on src/partials/header.html
> +                <li class="links-menu"><a href="#" class="links-item carrnet">О нас</a></li>
очепятка, надо current

2021-04-02 23:52 UTC, ol-nerium commented on src/partials/header.html
> +                <svg class="icon" width="14" height="20">
размер иконки меняется в мобильной и десктоп/таблетке. есть смысл задавать размер в scss, а не инлайн

2021-04-02 23:52 UTC, ol-nerium commented on src/partials/header.html
> +            <svg class="header-menu__icon" width="20" height="12">
2px срезались при выборе иконки на макете, размер 20.5 на 14 или 21 на 14, если округлить 
http://joxi.ru/v29MP14TpnzP02

2021-04-02 23:52 UTC, ol-nerium commented on src/partials/menu.html
> +        <svg class="modal-close" width="20" height="20">
размер иконки 14.5x14.5 http://joxi.ru/5mdbYE0T8MeQKA

2021-04-02 23:52 UTC, ol-nerium commented on src/partials/menu.html
> +        <p class="name"><span class="hell">адский</span> английский</p>
аналогично, как и с меню в шапке, "адский английский" должен быть кликатебельным вроде бы

2021-04-02 23:52 UTC, ol-nerium commented on src/partials/modal.html
> +                        <use href="./images/sprite.svg#icon-name"></use>
надо обновить спрайты или использовать те, которые уже есть, у нас нет иконок с такими айдишниками

2021-04-02 23:52 UTC, ol-nerium commented on src/partials/modal.html
> +                <use href="./images/sprite.svg#cross"></use>
нет такого айди в спрайте

2021-04-02 23:52 UTC, ol-nerium commented on src/partials/modal.html
> +                        <use href="./images/sprite.svg#icon-tube"></use>
нет такой иконки

2021-04-02 23:52 UTC, ol-nerium commented on src/partials/modal.html
> +        <p class="modal-haeding">Оставьте свои данные, мы вам перезвоним</p>
очепятка heading

2021-04-02 23:52 UTC, ol-nerium commented on src/partials/modal.html
> +                        <use href="./images/sprite.svg#icon-envelope"></use>
и тут

2021-04-02 23:52 UTC, ol-nerium commented on src/partials/modal.html
> +                    </svg>
Иконку чекбокса корректнее сделать не через спрайт, а пустым спаном, а в scss подключить background-image с кастомной иконкой : 

В modal.html вместо svg: 
// ...
span class="checkbox-submit__icon" (вместо svg class="modal-check__icon")
// ...

Реализация кастомного чекбокса _modal.scss  : 
// ...
.checkbox:checked ~ .modal-check__icon{
  background-color: $orange-text;
  background-image: url(../../images/checkbox.svg);
  background-size: contain;
  background-origin: border-box;
  border-color: $orange-text;
}

.modal-check__icon {
  display: inline-block;
  width: 16px;
  height: 15px;

  border: 1.78px solid $dark-text-bg;
  border-radius: 2px;
  margin-right: 8px;
}

// ...

2021-04-02 23:52 UTC, ol-nerium commented on src/sass/components/_header.scss
> +
width: 20.5px; (21px)
height: 14px; (2px срезаны)

2021-04-02 23:52 UTC, ol-nerium commented on src/sass/components/_header.scss
> +}
надо анимацию добавить 
можно добавить в спрайт id="icon-menu" fill:currentColor; 
а на кнопку задать color вместо fill, тогда цвет иконки будет меняться не только при ховере на саму иконку, но и при ховере на всю площадь кнопки

2021-04-02 23:52 UTC, al-burlachenko commented on src/sass/components/_header.scss
> +  margin-left: 25px;
margin-left: 40px;

2021-04-02 23:52 UTC, al-burlachenko commented on src/sass/components/_header.scss
> +}
надо анимацию

2021-04-02 23:52 UTC, al-burlachenko commented on src/sass/components/_modal.scss
> +.modal-haeding {
modal-heading

2021-04-02 23:52 UTC, al-burlachenko commented on src/sass/components/_modal.scss
> +  transition-timing-function: var(--cubic-bezier);
надо определить переменную --cubic-bezier или задать ее формулу в ручную, где надо

2021-04-02 23:52 UTC, al-burlachenko commented on src/index.js
> +import './modal';
недавно написали, что скрипты будем переносить и использовать в ./src/js/ http://joxi.ru/a2X8ZkxT4z4wG2

2021-04-03 01:43 UTC, al-burlachenko requested changes
Надо еще стили _menu.scss прописать

2021-04-03 01:43 UTC, al-burlachenko commented on src/sass/components/_header.scss
> +  }
letter-spacing: 0.18em;

2021-04-03 01:43 UTC, al-burlachenko commented on src/sass/components/_header.scss
> +  margin-top: 3px;
margin-top: 7px; 

font-size: 7px; , я думаю 
если line-height: 1.25; коэффициент высоты для всех шрифтов этих элементов

2021-04-03 01:43 UTC, al-burlachenko commented on src/sass/components/_header.scss
> +    line-height: 32px;
letter-spacing: 0.04em;

можно задать line-height: 1.23;

2021-04-03 01:43 UTC, al-burlachenko commented on src/sass/components/_header.scss
> +  font-size: 12px;
// line-height: 1.25; 
  // letter-spacing: 0.08em;

2021-04-03 01:43 UTC, al-burlachenko commented on src/sass/components/_header.scss
> +    font-size: 14px;
line-height: 1.21;
letter-spacing: 0.14em;

2021-04-03 01:43 UTC, al-burlachenko commented on src/sass/components/_header.scss
> +  line-height: 17px;
line-height: 1.22;

2021-04-03 03:31 UTC, al-burlachenko commented on src/partials/header.html
> +                <svg class="icon" width="14" height="20">
header__container надо задать отличные от контейнера паддинги, на мобилке это padding: 31px 20px 0px 20px; 
на таблетке padding: 40px 40px 70px 40px;

2021-04-03 03:52 UTC, al-burlachenko requested changes

2021-04-03 03:52 UTC, al-burlachenko commented on src/sass/components/_modal.scss
> +  width: 310px;
Думаю, стоит задать вместо фиксированной геометрии min-width и min-height

2021-04-03 03:52 UTC, al-burlachenko commented on src/sass/components/_modal.scss
> +  background-color: var(--font-modal);
переменную --font-modal надо определить

2021-04-03 03:52 UTC, al-burlachenko commented on src/sass/components/_modal.scss
> +  background-color: var(--text-color);
нет переменной --text-color

2021-04-03 03:52 UTC, al-burlachenko commented on src/sass/components/_modal.scss
> +  background-color: var(--text-color);
нет переменной

2021-04-03 03:52 UTC, al-burlachenko commented on src/sass/components/_modal.scss
> +    fill: var(--button-color);
нет переменной, надо все остальные значения с var переопределить

2021-04-03 03:52 UTC, al-burlachenko commented on src/partials/modal.html
> +                    </svg>
Также надо будет позиционировать чекбокс рядом с текстом

2021-04-03 09:30 UTC, Dmytro78 commented on src/partials/header.html
> +            <p class="name"><span class="hell">адский</span> английский</p>
убрал ссылку

2021-04-03 09:51 UTC, Dmytro78 commented on src/partials/header.html
> +                <li class="links-menu"><a href="#" class="links-item">Программы обучения</a></li>
пусть так будет а то сильно накручено получиться

2021-04-03 09:53 UTC, Dmytro78 commented on src/partials/header.html
> +                <li class="links-menu"><a href="#" class="links-item carrnet">О нас</a></li>
поменял

2021-04-03 09:54 UTC, Dmytro78 commented on src/partials/header.html
> +                <svg class="icon" width="14" height="20">
поменял

2021-04-03 09:59 UTC, Dmytro78 commented on src/partials/header.html
> +            <svg class="header-menu__icon" width="20" height="12">
20/14 у меня машина ругаеться на запятые

2021-04-03 10:02 UTC, Dmytro78 commented on src/sass/components/_header.scss
> +  margin-left: 25px;
там не правильные размеры когда 40рх они в два ряда становятся я специально уменьшил вчера на митинге обсуждали

2021-04-03 10:03 UTC, Dmytro78 commented on src/index.js
> +import './modal';
сделал

2021-04-03 10:05 UTC, Dmytro78 commented on src/sass/components/_header.scss
> +    line-height: 32px;
+

2021-04-03 10:06 UTC, Dmytro78 commented on src/sass/components/_header.scss
> +    line-height: 32px;
добавил

2021-04-03 10:09 UTC, Dmytro78 commented on src/sass/components/_modal.scss
> +  width: 310px;
пока не делал она не обязательна потом после менюхи займемся или хочеш поюзай там форма на свое усмотрение я думаю надо оставить окно коментария и все

2021-04-03 10:10 UTC, Dmytro78 commented on src/sass/components/_modal.scss
> +  background-color: var(--font-modal);
-

2021-04-03 10:11 UTC, Dmytro78 commented on src/sass/components/_modal.scss
> +  background-color: var(--text-color);
это скрыто

2021-04-03 10:27 UTC, al-burlachenko commented on src/partials/header.html
> +                <li class="links-menu"><a href="#" class="links-item">Программы обучения</a></li>
Мне кажется, если написать по-другому, будет легче понять, что есть что другим ребятам, если надо будет поддерживать код или тебе, если ты зайдешь через n-ное количество времени. 
Но мы вроде бы не делаем все строго по методологии и вряд ли будем поддерживать этот код в дальнейшем, так что ладно.

2021-04-03 10:38 UTC, al-burlachenko commented on src/sass/components/_modal.scss
> +  width: 310px;
Понял, но открытие/закрытие формы уже работает вроде бы. Надо только подправить геометрию и для форм может быть реализовываться отправка без перезагрузки страницы. В общем, на это действительно может не хватить времени, но было бы неплохо подправить немного геометрию формы хотя бы.

2021-04-03 18:50 UTC, sepaev commented on src/js/mobile-menu.js
> +  // Закрываем мобильное меню на более широких экранах
У нас перелом 1280 уже для десктопа идет верстка.. в ней модалка не предусмотрена. 
должен стоять параметр наподобии такого "@media (min-width: 1280px) {display:none;} " чтоб если перевернет планшет - то вообще убралось и модалка и кнопка модалки

2021-04-03 18:53 UTC, sepaev commented on src/partials/header.html
> +                <li class="links-menu"><a href="#" class="links-item">Программы обучения</a></li>
поменяй вот так:
  <ul class="menu">
                <li class="menu__links"><a href="#" class="menu__item">Программы обучения</a></li>

2021-04-03 18:57 UTC, sepaev commented on src/partials/menu.html
> +    <button class="menu-button js-close-menu">
menu__button

a svgшку вот так menu__button--close или menu__button-close

2021-04-03 18:59 UTC, sepaev commented on src/partials/menu.html
> +            <svg class="icon" width="14" height="20">
menu__logo-link для ссылки
menu__logo-icon для иконки

2021-04-03 19:01 UTC, sepaev commented on src/partials/menu.html
> +            <li class="mobile-menu__links"><a href="#" class="mobile-menu__item mobile-menu__item--carrnet">О нас</a></li>
опечатка нужно current, не carrent

2021-04-03 19:02 UTC, sepaev commented on src/partials/modal.html
> +            <svg class="modal-close" width="11" height="11">
modal__btn
modal__close

2021-04-03 19:04 UTC, sepaev commented on src/partials/modal.html
> +                <use href="./images/sprite.svg#cross"></use>
в спрайте он называется icon-close

2021-04-03 19:05 UTC, sepaev commented on src/partials/modal.html
> +        <p class="modal-haeding">Оставьте свои данные, мы вам перезвоним</p>
modal__heading не haeding

2021-04-03 19:06 UTC, sepaev commented on src/partials/modal.html
> +                        <use href="./images/sprite.svg#icon-name"></use>
https://trello-attachments.s3.amazonaws.com/6064b309baa92f21eccbfe69/972x850/6a24883d43f4555f22501a4124f76135/%D1%81%D0%BF%D1%80%D0%B0%D0%B9%D1%82.JPG.jpg

2021-04-03 19:13 UTC, sepaev commented on src/sass/components/_header.scss
> +
это подключается в common если чего то нет - добавь это общие стили

2021-04-03 19:15 UTC, sepaev commented on src/sass/components/_menu.scss
> +  transform: translateY(0);
если не ошибаюсь тут нужно медиа запрос чтоб не выполнялось условие если планшет перевернут

2021-04-03 19:17 UTC, sepaev commented on src/sass/components/_modal.scss
> +  transform: translate(-50%, -50%) scaleY(0);
тут тоже можно медиа запрос добавить на 1280px выше не нужно выполнять

2021-04-04 09:12 UTC, Dmytro78 commented on src/partials/header.html
> +                <li class="links-menu"><a href="#" class="links-item">Программы обучения</a></li>
+

2021-04-04 09:12 UTC, Dmytro78 commented on src/partials/menu.html
> +    <button class="menu-button js-close-menu">
+

2021-04-04 09:12 UTC, Dmytro78 commented on src/sass/components/_header.scss
> +
+

2021-04-04 09:12 UTC, Dmytro78 commented on src/sass/components/_header.scss
> +  margin-top: 3px;
-

2021-04-04 09:13 UTC, Dmytro78 commented on src/partials/modal.html
> +                <use href="./images/sprite.svg#cross"></use>
+

2021-04-04 09:19 UTC, Dmytro78 commented on src/js/mobile-menu.js
> +  // Закрываем мобильное меню на более широких экранах
оно в  js прописано строка 23-28
window.matchMedia('(min-width: 1280px)').addEventListener('change', e => {
    if (!e.matches) return;
    mobileMenu.classList.remove('is-open');
    openMenuBtn.setAttribute('aria-expanded', false);
    bodyScrollLock.enableBodyScroll(document.body);
  });

2021-04-04 09:19 UTC, Dmytro78 commented on src/sass/components/_modal.scss
> +  transform: translate(-50%, -50%) scaleY(0);
это модалка а не менюха

2021-04-04 09:21 UTC, Dmytro78 commented on src/sass/components/_menu.scss
> +  transform: translateY(0);
в js прописано или дублировать

2021-04-04 17:05 UTC, sepaev approved these changes, later dismissed

2021-04-04 18:09 UTC, merged